version: '3.1'

services:
  app:
    build: .
#    image: sunrise_diamonds_app
    ports:
      - "5000:5000"
    environment:
      DB_DSN: postgresql+psycopg2://postgres:cleanarchitecture@database/sunrise
    depends_on:
      - database
  database:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: cleanarchitecture
      POSTGRES_DB: sunrise